base_url = "https://iliana.fyi"
title = "iliana.fyi"
description = "iliana’s blog"
minify_html = true
generate_feed = true
ignored_content = [".*.swp"]

[markdown]
highlight_code = true
highlight_theme = "css"
# these are stored outside of `static/` so they can be `@import`ed into the right spots of styles.css, and are checked
# into version control to avoid a cyclical dependency.
highlight_themes_css = [
  { theme = "ayu-dark", filename = "../lib/css/code-dark.css" },
  { theme = "ayu-light", filename = "../lib/css/code-light.css" },
]
smart_punctuation = true

[extra]
