base_url = "https://iliana.fyi"
title = "iliana.fyi"
description = "iliana’s blog"
minify_html = true
generate_feed = true
ignored_content = [".*.swp"]

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"
smart_punctuation = true

[extra]
