base_url = "https://iliana.fyi"
title = "iliana.fyi"
description = "iliana’s blog"
generate_feed = true

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"
smart_punctuation = true

[extra]
