name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: tailscale/github-action@e870a1112fcc1faeeeeea3c1b0ce544e5ad01844
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - run: npm ci
        env:
          NODE_ENV: production
      - run: curl -fsSL https://github.com/getzola/zola/releases/download/v0.16.0/zola-v0.16.0-x86_64-unknown-linux-gnu.tar.gz | tar -xzC node_modules/.bin
      - run: echo "068e4448e409bb1f5ee5e925d8667e1d95c639f1a86b780e4e28e2eb10de1c5a  node_modules/.bin/zola" | sha256sum -c

      - run: npm run build
      - run: rsync -avc public/ www-deploy@dreamweaver:/srv/iliana.fyi/
