name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: tailscale/github-action@8b804aa882ac3429b804a2a22f9803a2101a0db9
        env:
          TS_EXPERIMENT_OAUTH_AUTHKEY: true
        with:
          authkey: "${{ secrets.TS_OAUTH_CLIENT_SECRET }}"
          version: 1.42.0
          args: --advertise-tags tag:www-deploy

      - name: Build
        run: |
          pipx install fonttools
          pipx inject fonttools brotli
          NODE_ENV=production npm ci
          npm run build

      - name: Set up SSH agent
        run: |
          eval `ssh-agent -s`
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >>"$GITHUB_ENV"
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        env:
          SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Deploy
        run: |
          mkdir ~/.ssh
          cp .github/workflows/known_hosts ~/.ssh/known_hosts
          rsync -av --checksum --delete-after --omit-dir-times public/ www-deploy@hydrangea:/var/www/iliana.fyi/
